/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hotelaria;
import DAO.AtendenteDAO;
import DTO.Atendente;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class Atendente_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Atendente_JFrame
     */
    public Atendente_JFrame() {
        initComponents();
        carregarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        menuItem1 = new javax.swing.JPanel();
        icoAtendente1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuItem2 = new javax.swing.JPanel();
        icoAtendente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuItem3 = new javax.swing.JPanel();
        icoAtendente2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuItem5 = new javax.swing.JPanel();
        icoAtendente4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menuItem6 = new javax.swing.JPanel();
        icoAtendente5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menuItem7 = new javax.swing.JPanel();
        icoAtendente6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuItem8 = new javax.swing.JPanel();
        icoAtendente7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        titleBar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        closePane = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JPanel();
        Salvar = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        paneForm = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cmpNome = new javax.swing.JTextField();
        cmpEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmpSenha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmpCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAtendente = new javax.swing.JTable();
        btnSalvar2 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JLabel();
        btnSalvar5 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JLabel();
        btnSalvar8 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(242, 242, 242));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(53, 33, 89));

        menuItem1.setBackground(new java.awt.Color(85, 65, 118));
        menuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem1MouseClicked(evt);
            }
        });

        icoAtendente1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        icoAtendente1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icoAtendente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_user_account_20px_1.png"))); // NOI18N
        icoAtendente1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Controle de Atendentes");

        javax.swing.GroupLayout menuItem1Layout = new javax.swing.GroupLayout(menuItem1);
        menuItem1.setLayout(menuItem1Layout);
        menuItem1Layout.setHorizontalGroup(
            menuItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icoAtendente1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuItem1Layout.setVerticalGroup(
            menuItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoAtendente1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuItem2.setBackground(new java.awt.Color(85, 65, 118));
        menuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem2MouseClicked(evt);
            }
        });

        icoAtendente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        icoAtendente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icoAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_booking_20px_1.png"))); // NOI18N
        icoAtendente.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Realizar uma Reserva");

        javax.swing.GroupLayout menuItem2Layout = new javax.swing.GroupLayout(menuItem2);
        menuItem2.setLayout(menuItem2Layout);
        menuItem2Layout.setHorizontalGroup(
            menuItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icoAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuItem2Layout.setVerticalGroup(
            menuItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuItem3.setBackground(new java.awt.Color(85, 65, 118));
        menuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem3MouseClicked(evt);
            }
        });

        icoAtendente2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        icoAtendente2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icoAtendente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_paper_20px.png"))); // NOI18N
        icoAtendente2.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Reemitir Nota Fiscal");

        javax.swing.GroupLayout menuItem3Layout = new javax.swing.GroupLayout(menuItem3);
        menuItem3.setLayout(menuItem3Layout);
        menuItem3Layout.setHorizontalGroup(
            menuItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icoAtendente2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuItem3Layout.setVerticalGroup(
            menuItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoAtendente2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuItem5.setBackground(new java.awt.Color(85, 65, 118));
        menuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem5MouseClicked(evt);
            }
        });

        icoAtendente4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        icoAtendente4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icoAtendente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_room_20px_1.png"))); // NOI18N
        icoAtendente4.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Controle de Quartos");

        javax.swing.GroupLayout menuItem5Layout = new javax.swing.GroupLayout(menuItem5);
        menuItem5.setLayout(menuItem5Layout);
        menuItem5Layout.setHorizontalGroup(
            menuItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icoAtendente4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuItem5Layout.setVerticalGroup(
            menuItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoAtendente4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuItem6.setBackground(new java.awt.Color(85, 65, 118));
        menuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icoAtendente5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        icoAtendente5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icoAtendente5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_documents_20px_1.png"))); // NOI18N
        icoAtendente5.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Relatórios");

        javax.swing.GroupLayout menuItem6Layout = new javax.swing.GroupLayout(menuItem6);
        menuItem6.setLayout(menuItem6Layout);
        menuItem6Layout.setHorizontalGroup(
            menuItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icoAtendente5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuItem6Layout.setVerticalGroup(
            menuItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoAtendente5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuItem7.setBackground(new java.awt.Color(85, 65, 118));
        menuItem7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icoAtendente6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        icoAtendente6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icoAtendente6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_hotel_20px.png"))); // NOI18N
        icoAtendente6.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Controle de Hospedagem");

        javax.swing.GroupLayout menuItem7Layout = new javax.swing.GroupLayout(menuItem7);
        menuItem7.setLayout(menuItem7Layout);
        menuItem7Layout.setHorizontalGroup(
            menuItem7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icoAtendente6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuItem7Layout.setVerticalGroup(
            menuItem7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoAtendente6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logo.setOpaque(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Night Owl Inn");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_owl_50px.png"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(32, 32, 32))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(32, 32, 32))
        );

        menuItem8.setBackground(new java.awt.Color(85, 65, 118));
        menuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem8MouseClicked(evt);
            }
        });

        icoAtendente7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        icoAtendente7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icoAtendente7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_customer_20px.png"))); // NOI18N
        icoAtendente7.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("Controle de Clientes");

        javax.swing.GroupLayout menuItem8Layout = new javax.swing.GroupLayout(menuItem8);
        menuItem8.setLayout(menuItem8Layout);
        menuItem8Layout.setHorizontalGroup(
            menuItem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(icoAtendente7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuItem8Layout.setVerticalGroup(
            menuItem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoAtendente7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuItem2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuItem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuItem5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuItem6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuItem7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menuItem8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(menuItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        titleBar.setBackground(new java.awt.Color(122, 72, 221));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hello bruh! This is your management system! uuul");

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        bg.add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 57, 660, 120));

        closePane.setBackground(new java.awt.Color(53, 33, 89));
        closePane.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N

        X.setBackground(new java.awt.Color(53, 33, 89));
        X.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        X.setForeground(new java.awt.Color(255, 255, 255));
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("x");
        X.setToolTipText("");
        X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closePaneLayout = new javax.swing.GroupLayout(closePane);
        closePane.setLayout(closePaneLayout);
        closePaneLayout.setHorizontalGroup(
            closePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        closePaneLayout.setVerticalGroup(
            closePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(closePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 40));

        mainPane.setOpaque(false);

        btnSalvar.setBackground(new java.awt.Color(122, 72, 221));
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Salvar.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Salvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salvar.setText("Salvar");
        Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSalvarLayout = new javax.swing.GroupLayout(btnSalvar);
        btnSalvar.setLayout(btnSalvarLayout);
        btnSalvarLayout.setHorizontalGroup(
            btnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnSalvarLayout.setVerticalGroup(
            btnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneForm.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Email atendente:");

        cmpNome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        cmpEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Nome atendente:");

        cmpSenha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Senha atendente:");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("ID Atendente:");

        cmpCodigo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneFormLayout = new javax.swing.GroupLayout(paneForm);
        paneForm.setLayout(paneFormLayout);
        paneFormLayout.setHorizontalGroup(
            paneFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFormLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paneFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmpSenha)
                    .addComponent(cmpNome)
                    .addComponent(cmpEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneFormLayout.createSequentialGroup()
                        .addGroup(paneFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmpCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(0, 446, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneFormLayout.setVerticalGroup(
            paneFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro e Edição", paneForm);

        tableAtendente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email"
            }
        ));
        tableAtendente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAtendenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAtendente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista todos atendentes", jPanel1);

        btnSalvar2.setBackground(new java.awt.Color(122, 72, 221));
        btnSalvar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnEditar.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSalvar2Layout = new javax.swing.GroupLayout(btnSalvar2);
        btnSalvar2.setLayout(btnSalvar2Layout);
        btnSalvar2Layout.setHorizontalGroup(
            btnSalvar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnSalvar2Layout.setVerticalGroup(
            btnSalvar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        btnSalvar5.setBackground(new java.awt.Color(122, 72, 221));
        btnSalvar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnExcluir.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSalvar5Layout = new javax.swing.GroupLayout(btnSalvar5);
        btnSalvar5.setLayout(btnSalvar5Layout);
        btnSalvar5Layout.setHorizontalGroup(
            btnSalvar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        btnSalvar5Layout.setVerticalGroup(
            btnSalvar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        btnSalvar8.setBackground(new java.awt.Color(122, 72, 221));
        btnSalvar8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBuscar.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSalvar8Layout = new javax.swing.GroupLayout(btnSalvar8);
        btnSalvar8.setLayout(btnSalvar8Layout);
        btnSalvar8Layout.setHorizontalGroup(
            btnSalvar8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        btnSalvar8Layout.setVerticalGroup(
            btnSalvar8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        lblMensagem.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPaneLayout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMensagem))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 197, 630, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        this.dispose();
    }//GEN-LAST:event_XMouseClicked

    private void SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseClicked
        Atendente obj = new Atendente(null, null, null);
        obj.setNome(cmpNome.getText());
        obj.setEmail(cmpEmail.getText());
        obj.setSenha(cmpSenha.getText());
        AtendenteDAO dao = new AtendenteDAO();
        if(dao.inserir(obj) > 0){
            limpar();
            atualizarLista(dao);
            lblMensagem.setText("Registro Inserido com sucesso !");
        } else {
            lblMensagem.setText("Registro não inserido !");
        }
    }//GEN-LAST:event_SalvarMouseClicked

    private void menuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem1MouseClicked
        Atendente_JFrame atendente = new Atendente_JFrame();
        this.dispose();
        atendente.setVisible(true);
    }//GEN-LAST:event_menuItem1MouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        int codigo = Integer.parseInt(cmpCodigo.getText());
        AtendenteDAO dao = new AtendenteDAO();
        if(dao.remover(codigo) > 0){
            limpar();
            atualizarLista(dao);
            lblMensagem.setText("Registro removido com sucesso !");
        } else {
            lblMensagem.setText("Registro não alterado !");
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void tableAtendenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAtendenteMouseClicked
        if(tableAtendente.getSelectedRow() != -1){
            Atendente obj = modelo.retornaObjeto(tableAtendente.getSelectedRow());
            cmpCodigo.setText(String.valueOf(obj.getCodigo()));
            cmpNome.setText(obj.getNome());
            cmpEmail.setText(obj.getEmail());
            cmpSenha.setText(obj.getSenha());
        }
    }//GEN-LAST:event_tableAtendenteMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        Atendente obj = new
                        Atendente(
                            cmpNome.getText(),
                            cmpEmail.getText(),
                            cmpSenha.getText()
                        );
        obj.setCodigo(Long.parseLong(cmpCodigo.getText()));
        AtendenteDAO dao = new AtendenteDAO();
        if(dao.alterar(obj) > 0){
            limpar();
            atualizarLista(dao);
            lblMensagem.setText("Registro alterado com sucesso !");
        } else {
            lblMensagem.setText("Registro não alterado !");
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        String cod = cmpCodigo.getText();
        String nome = cmpNome.getText();
        AtendenteDAO dao = new AtendenteDAO();
        Atendente obj = null;
        if(!"".equals(cod) ){
            obj = dao.pesquisarPorCodigo(Integer.parseInt(cod));
        }else if(!"".equals(nome)){
            obj = dao.pesquisarPorNome(nome);
        }else{
            lblMensagem.setText("Verifique os campos de busca!");
        }
        try{
        if(obj != null && obj.getCodigo() != 0){
            cmpNome.setText(obj.getNome());
            cmpEmail.setText(obj.getEmail());
            cmpSenha.setText(obj.getSenha());
            lblMensagem.setText("");

            atualizarLista(dao);
        }
        } catch(Exception e) {
            limpar();
            lblMensagem.setText("Registro não existe !");
            atualizarLista(dao);
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void menuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem2MouseClicked
        Reserva_JFrame reserva = new Reserva_JFrame();
        
        this.dispose();
        reserva.setVisible(true);
    }//GEN-LAST:event_menuItem2MouseClicked

    private void menuItem8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem8MouseClicked
        Cliente_JFrame cliente = new Cliente_JFrame();

        this.dispose();
        cliente.setVisible(true);
    }//GEN-LAST:event_menuItem8MouseClicked

    private void menuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem5MouseClicked
        Quarto_JFrame quarto = new Quarto_JFrame();

        this.dispose();
        quarto.setVisible(true);
    }//GEN-LAST:event_menuItem5MouseClicked

    private void menuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem3MouseClicked
        Nota_JFrame nota = new Nota_JFrame();

        this.dispose();
        nota.setVisible(true);
    }//GEN-LAST:event_menuItem3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atendente_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atendente_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atendente_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atendente_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atendente_JFrame().setVisible(true);
            }
        });
    }
    
    
    private void limpar(){
            cmpCodigo.setText("");
            cmpNome.setText("");
            cmpSenha.setText("");
            cmpEmail.setText("");   
    }

    private void atualizarLista(AtendenteDAO dao){
    modelo.setDados(dao.retornaLista(cmpNome.getText()));
    modelo.fireTableDataChanged();  
    }
    AtendenteTableModel modelo = new AtendenteTableModel(); 
 
    private void carregarLista(){
        AtendenteDAO dao = new AtendenteDAO();
        modelo.setDados(dao.retornaLista(""));
        tableAtendente.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salvar;
    private javax.swing.JLabel X;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnExcluir;
    private javax.swing.JPanel btnSalvar;
    private javax.swing.JPanel btnSalvar2;
    private javax.swing.JPanel btnSalvar5;
    private javax.swing.JPanel btnSalvar8;
    private javax.swing.JPanel closePane;
    private javax.swing.JTextField cmpCodigo;
    private javax.swing.JTextField cmpEmail;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JTextField cmpSenha;
    private javax.swing.JLabel icoAtendente;
    private javax.swing.JLabel icoAtendente1;
    private javax.swing.JLabel icoAtendente2;
    private javax.swing.JLabel icoAtendente4;
    private javax.swing.JLabel icoAtendente5;
    private javax.swing.JLabel icoAtendente6;
    private javax.swing.JLabel icoAtendente7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel menuItem1;
    private javax.swing.JPanel menuItem2;
    private javax.swing.JPanel menuItem3;
    private javax.swing.JPanel menuItem5;
    private javax.swing.JPanel menuItem6;
    private javax.swing.JPanel menuItem7;
    private javax.swing.JPanel menuItem8;
    private javax.swing.JPanel paneForm;
    private javax.swing.JPanel sidepane;
    private javax.swing.JTable tableAtendente;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
